version: '3.9'
services:
  app:
    container_name: friendzone-server-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - PG_USER=friendzone
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=friendzone
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dorta.dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  pgdata: {}
